addSbtPlugin("org.jetbrains.scala"          % "sbt-ide-settings"         % "1.1.1")
addSbtPlugin("org.scala-js"                 % "sbt-scalajs"              % "1.13.2")
addSbtPlugin("com.disneystreaming.smithy4s" % "smithy4s-sbt-codegen"     % "0.18.3")
addSbtPlugin("org.portable-scala"           % "sbt-scalajs-crossproject" % "1.2.0")
addSbtPlugin("com.github.sbt"               % "sbt-native-packager"      % "1.9.11")
